### ISSUE TITLE
All activity screen is empty (FW10.0 Atmosphere 0.11.1)

### ISSUE THREAD

**Issue by brlala** [tallbl0nde/NX-Activity-Log#33]
Attached the playlog. Used to be working fine before, now the all activity log screen doesn't show anything. Recent Activity shows the hours played but not the Titles
[playlog.txt](https://github.com/tallbl0nde/NX-Activity-Log/files/4496271/playlog.txt)

**Comment by jimfuss** [comment]
Can confirm the same issue. Stopped working just as I updated to 10.0 with Atmosphere 0.11.1. Also tested with version 1.2 (aside from the 1.2.2 latest) and it has the same issue.
![recent_activity](https://user-images.githubusercontent.com/24627711/79634032-5e7c2e80-8168-11ea-999e-3d6a4d205b9a.jpg)
![all_activity](https://user-images.githubusercontent.com/24627711/79634030-5d4b0180-8168-11ea-9454-2c1edd27194d.jpg)

**Comment by tallbl0nde** [comment]
Dang I didn't think a firmware update would actually break this :/

From what I can see the playtime side of things is still working but actually getting a list of installed titles is failing and thus that's why both lists are empty. While I will try to look into this it may take a while as I don't intend to upgrade to 10.0.0 just yet. 

Are either of you having issues with other homebrew such as Goldleaf where it displays titles on the system?

Hopefully it just requires a libnx update!

**Comment by jimfuss** [comment]
I just tried Goldleaf and EdiZon and both seem to be able display the list of installed titles as before. I don't use either all that much but it looks they still work as intended on 10.0.

Hopefully this can be fixed, thanks for the amazing application!

**Comment by tallbl0nde** [comment]
Thanks for the info, it must have something to do with playdata module then. I'll try to fix it when I can!

**Comment by tallbl0nde** [comment]
Since I'm not on 10.0.0 I've just written some code to log what the app is doing in terms of reading users/titles/playtime... so it would be great if someone could help me test by doing the following:

1) Run the attached .nro (it will still appear the same as v1.2.2)
2) Once you get to the user select screen (it may take a while) go to recent activity
3) Then go to all activity
4) Then quit

There should be two files at the root of your SD card:
- nx-a-l_NX.txt
- nx-a-l_PD.txt

Please upload them here! You're of course then free to delete the log files.
[NX-Activity-Log 10.0.0 Test.zip](https://github.com/tallbl0nde/NX-Activity-Log/files/4498450/NX-Activity-Log.10.0.0.Test.zip)

**Comment by brlala** [comment]
[nx-a-l_NX.txt](https://github.com/tallbl0nde/NX-Activity-Log/files/4498470/nx-a-l_NX.txt)
as for the `nx-a-l_PD.txt` , it's empty so I couldn't upload it up over here

**Comment by tallbl0nde** [comment]
Thanks that's fine, it actually helps out quite a bit! So like I thought - it can't read which games are installed... I'll look into it!

**Comment by tallbl0nde** [comment]
Could you give this version a shot? It should fix the problem.
[NX-Activity-Log.zip](https://github.com/tallbl0nde/NX-Activity-Log/files/4498490/NX-Activity-Log.zip)

**Comment by brlala** [comment]
The version you posted seems to be working now! Is it normal for the Activity for today to be empty? and that the time used is in GMT instead of the local timezone?

**Comment by tallbl0nde** [comment]
The time should be fixed in the next release, it was due to a bug in libnx. Unless it was correct before you updated and it's wrong now?

It shouldn't be empty if you've actually played something today - I've noticed it only updates when you close a game.

**Comment by brlala** [comment]
everything seems to be working correctly now! Yes you're correct I'd need to close my game for it to update correctly. As for the timezone issue, I remember reporting the bug for times not considering timezone in libnx before but that was a long way back(and I remember a fix was pushed back then). I didn't pay much attention to how it was before the updates, but I assume it disregards the timezone as well

Thanks again!
